// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agqymtcenpazzxzojrll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncXltdGNlbnBhenp4em9qcmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzc0ODQsImV4cCI6MjA1ODcxMzQ4NH0.Ck1AyiHSS1x2cffRwqJ-ce42LeWlmWQMOTBCZ3W1cl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);